quiz_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from quiz_app import views
from quiz_app.views import quiz_list,take_quiz,quiz_score

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from quiz_app.api import QuizViewSet  


router = DefaultRouter()
router.register(r'quizzes', QuizViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    
    #Quiz Urls
    path('quiz_list/', quiz_list, name='quiz_list'),
    path('quiz/<int:quiz_id>/', take_quiz, name='take_quiz'),
    path('quiz/<int:quiz_id>/score/', quiz_score, name='quiz_score'),
    #ApI route Path
    path('/api', include(router.urls)),
    
]

quiz_app/models.py
# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.db import models

class CustomUser(AbstractUser):
    # Assuming 'name' is additional to the standard 'first_name' and 'last_name'
    name = models.CharField(max_length=255, null=True, blank=True)
    # Gender field with choices
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, null=True, blank=True)

User = get_user_model()

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.text

class AnswerOption(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

class QuizAttempt(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='attempts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='attempts')
    date_attempted = models.DateTimeField(auto_now_add=True)
    score = models.IntegerField(null=True, blank=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}'s attempt at {self.quiz.title} on {self.date_attempted}"

class UserAnswer(models.Model):
    quiz_attempt = models.ForeignKey(QuizAttempt, on_delete=models.CASCADE, related_name='user_answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selected_answer = models.ForeignKey(AnswerOption, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"Answer to {self.question.text} by {self.quiz_attempt.user}: {self.selected_answer.text}"

quiz_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2', 'name', 'gender']

quiz_app/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login as auth_login, logout
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render, redirect
from .models import Quiz, Question, AnswerOption, QuizAttempt, UserAnswer



def register(request):
    if request.method == 'POST':
         # Manually capture form data
        username = request.POST['username']
        email = request.POST['email']
        name = request.POST['name']
        gender = request.POST['gender']
        password = request.POST['password1']
        confirm_password = request.POST['password2']
        User = get_user_model()
        
        #Checking if the email is already exist
        if User.objects.filter(email=email).exists():
            return HttpResponse("Email already exists. Please use a different email address.")
        if User.objects.filter(username=username).exists():
            return HttpResponse("Username already exists. Please use a different username.")
        
        # Check if the two passwords match
        if password != confirm_password:
            return HttpResponse("Passwords do not match!")
       
        user = User.objects.create(username=username, email=email, password=make_password(password))
        
        user.name = name
        user.gender = gender
        user.save()

        messages.success(request, f'Account created for {username}!')
        return redirect('login')  
    else:
        form = UserRegisterForm()
    return render(request, 'quiz_app/register.html', {'form': form})


def home(request):
    return render(request, 'quiz_app/home.html')

# Contact view
def contact(request):
    return render(request, 'quiz_app/contact.html')

# Login view
def user_login(request):
     if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')

        # Authenticating the user
        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            # Redirect to a success page.
            return redirect('quiz_list')  
        else:
            # Return an 'invalid login' error message.
            messages.error(request, 'Invalid username or password.')

     return render(request, 'quiz_app/login.html')

def user_logout(request):
    logout(request)
    # Redirect to login page after logout
    return redirect('login')

#User view for Quizzes and other Related functionalities.

def quiz_list(request):
    quizzes = Quiz.objects.filter(active=True).order_by('-date_created')
    return render(request, 'quizzes/quiz_list.html', {'quizzes': quizzes})

from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from .models import Quiz, Question, AnswerOption, QuizAttempt, UserAnswer

 
def quiz_score(request, quiz_id):
    if not request.user.is_authenticated:
        # Redirect to login page or show an error
        return redirect('login')

    quiz_attempt = QuizAttempt.objects.filter(quiz_id=quiz_id, user=request.user).latest('date_attempted')
    return render(request, 'quizzes/quiz_score.html', {'quiz_attempt': quiz_attempt})

def take_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)

    if not request.user.is_authenticated:
        return redirect('login')

    # Check for an existing, non-completed attempt
    quiz_attempt = QuizAttempt.objects.filter(quiz=quiz, user=request.user, completed=False).first()

    if quiz_attempt is None:
        # If no ongoing attempt is found, check if the user has completed this quiz before
        if QuizAttempt.objects.filter(quiz=quiz, user=request.user, completed=True).exists():
            # Redirect to score page if they've completed it before
            return HttpResponseRedirect(f'/quiz/{quiz.id}/score/')
        else:
            # Start a new attempt if they haven't completed the quiz
            quiz_attempt = QuizAttempt.objects.create(
                quiz=quiz,
                user=request.user,
                score=0,
                completed=False  # Mark as ongoing
            )

    if request.method == 'POST':
        question_id = request.POST.get('question_id')
        selected_option_id = request.POST.get('answer')
        current_question = get_object_or_404(Question, id=question_id)

        if selected_option_id:
            selected_option = get_object_or_404(AnswerOption, id=selected_option_id)
            # Save the user's answer (if authenticated)
            UserAnswer.objects.create(
                quiz_attempt=quiz_attempt,
                question=current_question,
                selected_answer=selected_option,
                is_correct=selected_option.is_correct  
            )

        # Check if this was the last question and mark attempt as completed if it was
        questions = list(quiz.questions.all())
        current_question_index = questions.index(current_question)
        if current_question_index + 1 == len(questions):
            # Calculate score based on UserAnswer records
            correct_answers_count = UserAnswer.objects.filter(quiz_attempt=quiz_attempt, is_correct=True).count()
            quiz_attempt.score = correct_answers_count
            quiz_attempt.completed = True
            quiz_attempt.save()
            return HttpResponseRedirect(f'/quiz/{quiz.id}/score/')
        else:
            # Proceed to next question
            next_question = questions[current_question_index + 1]
            return render(request, 'quizzes/take_quiz.html', {'quiz': quiz, 'question': next_question})

    else:
        # If it's not a POST request, show the first question or the next unanswered question
        answered_questions_ids = UserAnswer.objects.filter(
            quiz_attempt=quiz_attempt).values_list('question_id', flat=True)
        next_question = quiz.questions.exclude(id__in=answered_questions_ids).first()

        if next_question:
            return render(request, 'quizzes/take_quiz.html', {'quiz': quiz, 'question': next_question})
        elif not quiz_attempt.completed:
            # This handles a rare case where all questions are answered but not marked as completed.
            correct_answers_count = UserAnswer.objects.filter(quiz_attempt=quiz_attempt, is_correct=True).count()
            quiz_attempt.score = correct_answers_count
            quiz_attempt.completed = True
            quiz_attempt.save()
            return HttpResponseRedirect(f'/quiz/{quiz.id}/score/')
        else:
            # Handle case with no questions or all questions have been answered.
            return HttpResponseRedirect(f'/quiz/{quiz.id}/score/')

quiz_app/templates/quiz_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RealQuizer</title>
     {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!-- Adjust the path as needed -->
</head>
<body>
    
    <nav class="custom-navbar">
        <a class="navbar-brand" href="{% url "quiz_list" %}">RealQuizer</a>
        <button class="navbar-toggler" type="button">
          <span class="toggler-icon">☰</span>
        </button>

        <div class="navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item active">
                {% if user.is_authenticated %}
                <a href="{% url 'quiz_list' %}" class="nav-link">Home</a>
                {% else %}
                <a href="{% url 'login' %}" class="nav-link">Home</a>
                {% endif %}
            </li>
            {% if user.is_authenticated %}
            
            {% else %}
            <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link">Register</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'contact' %}" class="nav-link">Contact Us</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}" class="dropdown-item">Login</a>
                {% endif %}
            </li>
           
          </ul>
          
        </div>
      </nav>
      
    

    <main id>
        <div class="container">
            {% block content %}
            <!-- Content from child templates will be inserted here -->
            {% endblock %}
        </div>
    </main>

    <footer>
        <div class="footer-container">
            &copy; 2024 RealQuizer. All rights reserved.
        </div>
    </footer>


    <script>
        document.querySelector('.navbar-toggler').addEventListener('click', function() {
            this.classList.toggle('active');
            document.querySelector('.navbar-collapse').classList.toggle('show');
        });
        </script>
</body>
</html>

quiz_app/templates/quiz_app/contact.html
{% extends "quiz_app/base.html" %}

{% block content %}
<div id="contact">
    <div class="containers">
        <h2>Contact Us</h2>
        <div class="contact-content">
            <form class="contact-form" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Message:</label>
                    <textarea id="message" name="message" rows="4" required></textarea>
                </div>
                <button type="submit" class="submit-btn">Send Message</button>
            </form>
            <div class="contact-image">
                {% load static %}
                <img src="{% static 'images/contact_images.jpg' %}" alt="Contact Us">
            </div>
        </div>
    </div>
</div>
{% endblock %}

quiz_app/templates/quiz_app/home.html
{% extends "quiz_app/base.html" %}  <!-- Adjust the path as needed -->

{% block content %}
<h2> Welcome</h2>
{% endblock %}

quiz_app/templates/quiz_app/login.html
{% extends "quiz_app/base.html" %}  <!-- Adjust the path as needed -->

{% block content %}
<div class="container-block">
    <h2 class="form-title">Welcome back to RealQuizer</h2>
    <form method="post" class="registration-form" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_email">Email</label>
            <input type="text" name="username"  id="id_username" required>
        </div>
        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" name="password1" id="id_password" required>
        </div>
    
        <button type="submit" class="submit-btn">Login</button>
    </form>
</div>
{% endblock %}

quiz_app/templates/quiz_app/register.html
{% extends "quiz_app/base.html" %}  <!-- Adjust the path as needed -->

{% block content %}
<div class="container-block">
    <h2 class="form-title">Join RealQuizer Today</h2>
    <form method="post" class="registration-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name</label>
            <input type="text" name="name" id="id_name" required>
        </div>
        <div class="form-group">
            <label>Gender</label>
            <select name="gender" required>
                <option value="">Select...</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_username">Username</label>
            <input type="text" name="username" id="id_username" required>
        </div>
        <div class="form-group">
            <label for="id_email">Email</label>
            <input type="email" name="email" id="id_email" required>
        </div>
        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" name="password1" id="id_password" required>
        </div>
        <div class="form-group">
            <label for="id_confirm_password">Confirm Password</label>
            <input type="password" name="password2" id="id_confirm_password" required>
        </div>
       
        <button type="submit" class="submit-btn">Register</button>
    </form>
</div>
{% endblock %}